```{r}
library(tidyverse)
```

```{r}
df <- read_csv("test1.csv")
```
```{r fig.height=12, fig.width=5}
df %>% 
  group_by(X5) %>% 
  summarise(amount=n()) %>% 
  arrange(desc(amount)) %>% 
  rename(name = X5) %>%
  mutate(name = as.character(name) %>% str_trunc(33, "right") %>% str_remove_all("th\\s") %>%  fct_reorder(amount)) %>% 
  drop_na() %>% 
  ggplot() +
  aes(amount, name, fill=name) +
  geom_col() +
  theme_minimal() +
  theme(legend.position="none") +
  scale_x_continuous(expand=c(0,0))
```

```{r}
GetCitations <- function(DOI){
  if(!is.na(DOI)){
    tryCatch(expr = {
      api <- paste0("https://opencitations.net/index/coci/api/v1/citations/",DOI)
      rjson::fromJSON(file = api) %>% 
        lapply(function(x){
          x[['citing']]
        }) %>% 
        unlist %>% 
        length() %>% 
        return
    }, error = function(cond){return(NA)},
    finally = function(cond){return(NA)})
  } 
  else {
    return(NA)
  }
}
```

